# Generated by Django 6.0 on 2025-12-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destinario', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado')], max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
