# Generated by Django 6.0 on 2025-12-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='nombre_destinario',
            new_name='nombre_destinatario',
        ),
    ]
