# Generated by Django 6.0 on 2025-12-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0002_rename_nombre_destinario_paquete_nombre_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='estado',
        ),
    ]
