# Generated by Django 6.0 on 2025-12-06 01:39

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0003_remove_paquete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='estado',
            field=django_fsm.FSMField(choices=[('CREADO', 'Creado'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado')], default='CREADO', max_length=50),
        ),
    ]
