# Generated by Django 6.0 on 2025-12-06 02:48

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0004_paquete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='estado',
            field=django_fsm.FSMField(choices=[('CREADO', 'CREADO'), ('EN TRANSITO', 'EN TRANSITO'), ('ENTREGADO', 'ENTREGADO')], default='CREADO', max_length=50, protected=True),
        ),
    ]
